apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-app
  template:
    metadata:
      labels:
        app: cloud-app
    spec:
      containers:
        - name: cloud-app
          image: asia-east1-docker.pkg.dev/YOUR_PROJECT/YOUR_REPO/YOUR_IMAGE:latest
          ports:
            - containerPort: 3000
