name: Deploy to GKE

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  APP_NAME: cloud-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    environment:
      name: ${{ github.event.inputs.environment || 'staging' }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker asia-east1-docker.pkg.dev

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-repo/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} .
          docker push asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/hello-repo/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to GKE using Kustomize
        run: |
          curl -sfLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v4.5.7/kustomize_v4.5.7_linux_amd64.tar.gz
          tar -xzf kustomize.tar.gz
          chmod +x kustomize
          ./kustomize build kubernetes/overlays/${{ github.event.inputs.environment || 'staging' }} | kubectl apply -f -
          kubectl rollout status deployment/${{ secrets.KUBERNETES_DEPLOYMENT_NAME }} -n ${{ secrets.KUBERNETES_NAMESPACE }}
